-- Sequences (per user)
CREATE TABLE IF NOT EXISTS public.sequences (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  title text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT sequences_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES public.users(id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sequences_user_id
  ON public.sequences (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS unique_sequences_user_lower_title
  ON public.sequences (user_id, lower(title));

-- Sequence steps
CREATE TABLE IF NOT EXISTS public.sequence_steps (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sequence_id integer NOT NULL,
  step_number integer NOT NULL,
  offset_days integer NOT NULL DEFAULT 0,
  type text NOT NULL,
  title text NOT NULL,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT sequence_steps_sequence_id_fkey
    FOREIGN KEY (sequence_id)
    REFERENCES public.sequences(id)
    ON DELETE CASCADE,
  CONSTRAINT sequence_steps_type_check
    CHECK (type IN ('call', 'email', 'note')),
  CONSTRAINT sequence_steps_step_number_check
    CHECK (step_number > 0),
  CONSTRAINT sequence_steps_offset_days_check
    CHECK (offset_days >= 0),
  CONSTRAINT unique_sequence_steps_step_number
    UNIQUE (sequence_id, step_number)
);

CREATE INDEX IF NOT EXISTS idx_sequence_steps_sequence_id
  ON public.sequence_steps (sequence_id);

-- Leads: sequence state + follow-up timestamp
ALTER TABLE public.leads
ADD COLUMN IF NOT EXISTS sequence_id integer;

ALTER TABLE public.leads
ADD COLUMN IF NOT EXISTS current_step integer;

ALTER TABLE public.leads
ADD COLUMN IF NOT EXISTS next_follow_up_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'leads_sequence_id_fkey'
      AND conrelid = 'public.leads'::regclass
  ) THEN
    ALTER TABLE public.leads
    ADD CONSTRAINT leads_sequence_id_fkey
      FOREIGN KEY (sequence_id)
      REFERENCES public.sequences(id)
      ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'leads_current_step_positive_check'
      AND conrelid = 'public.leads'::regclass
  ) THEN
    ALTER TABLE public.leads
    ADD CONSTRAINT leads_current_step_positive_check
      CHECK (current_step IS NULL OR current_step > 0);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_leads_sequence_id
  ON public.leads (sequence_id);

CREATE INDEX IF NOT EXISTS idx_leads_user_next_follow_up_at
  ON public.leads (user_id, next_follow_up_at);

-- Activities: link completion to specific sequence step
ALTER TABLE public.lead_activities
ADD COLUMN IF NOT EXISTS sequence_step_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'lead_activities_sequence_step_id_fkey'
      AND conrelid = 'public.lead_activities'::regclass
  ) THEN
    ALTER TABLE public.lead_activities
    ADD CONSTRAINT lead_activities_sequence_step_id_fkey
      FOREIGN KEY (sequence_step_id)
      REFERENCES public.sequence_steps(id)
      ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_lead_activities_sequence_step_id
  ON public.lead_activities (sequence_step_id);
