CREATE TABLE IF NOT EXISTS public.user_credits (
  user_id uuid PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  balance integer NOT NULL DEFAULT 0,
  monthly_allocation integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_credits_balance_non_negative CHECK (balance >= 0),
  CONSTRAINT user_credits_monthly_allocation_non_negative CHECK (monthly_allocation >= 0)
);

CREATE TABLE IF NOT EXISTS public.credit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  amount integer NOT NULL,
  feature text NOT NULL,
  reference_id uuid NULL,
  description text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT credit_events_amount_non_zero CHECK (amount <> 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_credit_events_user_feature_reference_unique
ON public.credit_events (user_id, feature, reference_id)
WHERE reference_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_credit_events_user_created_at_desc
ON public.credit_events (user_id, created_at DESC);
