CREATE TABLE IF NOT EXISTS public.usage_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  feature text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  reference_id uuid NULL,
  metadata jsonb NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT usage_events_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_usage_events_user_feature_time
ON public.usage_events (user_id, feature, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_usage_events_feature_time
ON public.usage_events (feature, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_events_feature_reference_unique
ON public.usage_events (feature, reference_id)
WHERE reference_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.plan_limits (
  plan_tier text NOT NULL,
  feature text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  limit_value integer NULL,
  period text NOT NULL DEFAULT 'monthly',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (plan_tier, feature),
  CONSTRAINT plan_limits_limit_non_negative CHECK (limit_value IS NULL OR limit_value >= 0),
  CONSTRAINT plan_limits_period_check CHECK (period IN ('monthly', 'lifetime', 'none'))
);

CREATE INDEX IF NOT EXISTS idx_plan_limits_feature
ON public.plan_limits (feature);

INSERT INTO public.plan_limits (plan_tier, feature, enabled, limit_value, period)
VALUES
  ('free', 'activeIdeas', true, 2, 'lifetime'),
  ('free', 'archivedIdeas', true, 3, 'lifetime'),
  ('free', 'revisionsPerIdea', true, 30, 'lifetime'),
  ('free', 'freeformInterviewsPerIdeaPerMonth', true, 30, 'monthly'),
  ('free', 'structuredValidation', false, NULL, 'none'),
  ('growth', 'activeIdeas', true, 5, 'lifetime'),
  ('growth', 'archivedIdeas', true, 50, 'lifetime'),
  ('growth', 'revisionsPerIdea', true, NULL, 'lifetime'),
  ('growth', 'freeformInterviewsPerIdeaPerMonth', true, NULL, 'monthly'),
  ('growth', 'structuredValidation', true, NULL, 'none'),
  ('founder', 'activeIdeas', true, 5, 'lifetime'),
  ('founder', 'archivedIdeas', true, 100, 'lifetime'),
  ('founder', 'revisionsPerIdea', true, NULL, 'lifetime'),
  ('founder', 'freeformInterviewsPerIdeaPerMonth', true, NULL, 'monthly'),
  ('founder', 'structuredValidation', true, NULL, 'none')
ON CONFLICT (plan_tier, feature) DO UPDATE
SET
  enabled = EXCLUDED.enabled,
  limit_value = EXCLUDED.limit_value,
  period = EXCLUDED.period,
  updated_at = now();
