-- Users updates
ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS name text;

-- Pipeline stages
CREATE TABLE IF NOT EXISTS public.pipeline_stages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  position integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT pipeline_stages_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES public.users(id)
    ON DELETE CASCADE,
  CONSTRAINT unique_stage_position_per_user UNIQUE (user_id, position),
  CONSTRAINT unique_stage_name_per_user UNIQUE (user_id, name)
);

-- Leads
CREATE TABLE IF NOT EXISTS public.leads (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  company text,
  email text,
  stage_id integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT leads_stage_id_fkey
    FOREIGN KEY (stage_id)
    REFERENCES public.pipeline_stages(id)
    ON DELETE SET NULL,
  CONSTRAINT leads_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES public.users(id)
    ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_leads_stage_id ON public.leads(stage_id);
CREATE INDEX IF NOT EXISTS idx_leads_user_id ON public.leads(user_id);
CREATE INDEX IF NOT EXISTS idx_leads_email ON public.leads(email);
CREATE INDEX IF NOT EXISTS idx_pipeline_stages_user_id ON public.pipeline_stages(user_id);